### ISSUE TITLE
Let's clean up a bit in the repository

### ISSUE THREAD

**Issue by user-has-no-name** [katasee/mentorship#1]
There is a minor inconsistency in the repository structure. A folder named “day_2” has been created, but “day_1” is missing. I suggest creating a folder named “day_1” and moving all related files into it.

Additionally, I recommend organizing the repository by creating separate folders for each topic. For example, if there is a topic named “Constants”, create a dedicated folder for it and include the playground files and test results inside.

**Comment by katasee** [comment]
Done
