### ISSUE TITLE
Add .gitignore file

### ISSUE THREAD

**Issue by user-has-no-name** [katasee/mentorship#2]
The repository currently includes .DS_Store files, which are unnecessary for others and should be excluded. For more information on .DS_Store files, you can refer to this article: [What is a .DS_Store File?](https://techjd.medium.com/so-what-is-that-ds-store-file-anyway-2255022d0d83) (optional reading).

It’s a good practice to ignore these files by using a `.gitignore` file. This file allows you to specify files or extensions to exclude from the repository. To ignore `.DS_Store` files, create a `.gitignore` file and add `.DS_Store` to it. You can follow this [instruction](https://gist.github.com/lohenyumnam/2b127b9c3d1435dc12a33613c44e6308)

**Comment by katasee** [comment]
Done

**Comment by user-has-no-name** [comment]
Don't forget to add the `.gitignore' file :) The goal is to get rid of the `.DS_Store' files permanently.
